# Generated by Django 4.0.1 on 2022-06-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.URLField()),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=100)),
                ('totprice', models.IntegerField()),
                ('ppsqft', models.IntegerField()),
                ('Superarea', models.IntegerField()),
                ('Carpetarea', models.IntegerField()),
                ('ProjectName', models.CharField(max_length=50)),
                ('Furnishedstatus', models.CharField(max_length=50)),
                ('Overlooking', models.CharField(max_length=50)),
                ('CornerProperty', models.IntegerField()),
                ('Washrooms', models.IntegerField()),
                ('Carparking', models.CharField(max_length=50)),
                ('LEEDCertification', models.CharField(max_length=50)),
                ('BuildingClass', models.CharField(max_length=50)),
                ('Lifts', models.IntegerField()),
                ('WaterAvailability', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.URLField()),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('totprice', models.IntegerField()),
                ('Superarea', models.IntegerField()),
                ('Carpetarea', models.IntegerField()),
                ('ProjectName', models.CharField(max_length=200)),
                ('Furnishedstatus', models.CharField(max_length=200)),
                ('Overlooking', models.CharField(max_length=200)),
                ('CornerProperty', models.IntegerField()),
                ('Washrooms', models.IntegerField()),
                ('Carparking', models.CharField(max_length=50)),
                ('LEEDCertification', models.CharField(max_length=50)),
                ('BuildingClass', models.CharField(max_length=50)),
                ('ConstructionStatus', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('mintotprice', models.IntegerField()),
                ('maxtotprice', models.IntegerField()),
                ('superarea', models.IntegerField()),
            ],
        ),
    ]
